name: Middleware Service Workflow - Production

on:
  pull_request:
    branches:
      - production
    types:
      - closed

# Later, in the jobs section of your actions.yml file.
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
        BASE-IMAGE: josleke/middleware-service
        RELEASE-TAG: 2024.8.10-Release
    steps:
      - run: |
          echo The PR was successfully merged.